version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dmarc-report-lambda"
s3_prefix = "dmarc_report_lambda"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
