name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Build
      run: go build -v -tags lambda.norpc ./...

    - name: Test
      run: go test -tags lambda.norpc -covermode="count" -coverprofile="/tmp/coverage.out"
      
    - name: Coverage Report
      run: go tool cover -func="/tmp/coverage.out"

